// questions/dares.js

module.exports = [
  "Do 10 push-ups right now.",
  "Text your crush 'I need to talk... 😳'",
  "Do a cringe dance move on camera.",
  "Speak in a baby voice until your next turn.",
  "Let the group choose a nickname for you.",
  "Post a funny selfie in the group chat.",
  "Impersonate another player for 30 seconds.",
  "Sing the chorus of your favorite song out loud.",
  "Post the last DM you sent to anyone (no edits).",
  "Send “I have feelings for you” to the 5th person in your DMs. No context.",
  "Share your screen and show your YouTube search history.",
  "Speak in slow motion for your next two responses.",
  "Show the last photo you took and explain the story behind it.",
  "Mimic a dramatic breakup scene from a movie—with someone in the group.",
  "Scroll to a random contact and send them “What’s the meaning of life?",
  "Choose someone in the group and say why they’d make a terrible partner.",
  "Let the group ask you any one “Would you rather” — and answer it honestly.",
  "Post “I miss you 💔” on your WhatsApp/Instagram story for 10 minutes.",
  "Pick a player and say what you'd do if you were both alone right now.",
  "Put your fingers in your mouth and say, “Oops. Was that inappropriate?",
  "Name one object around you you could technically use in bed.",
  "Explain what you think “good sex” really means, no clichés.",
  "Act out how you’d beg if someone had you handcuffed(u can ask chatgpt & read out loud what it you )",
  "Call a friend and ask them how they feel about showering together as a social experiment",
  "Pick the friend in the group you trust the least — and explain.",
  "Say one harsh truth about each person in the room. No soft lies.",
  "Expose the pettiest reason you’ve ever hated someone in this group",
   "Call a mutual friend and ask: ‘Out of the people in this room, who do you think is most insecure",
   "Who in this group would you never date, even if they were the last person alive?",


];
